### ISSUE TITLE
Moderation data type implementation

### ISSUE THREAD

**Issue by micahscopes** [hyperhyperspace/wiki-collab#6]
To do:
- owners and members sets
- permissions: **`Page.blocks`** and **`Block.contents`**
  - for each permission, a `CausalSet` with `allowedMembers` representing **owners**, **members**, **anybody**.
  - for each permission, validation logic requiring two simultaneous attestations:
    1. that a given group has editing permissions and
    2. that the author is a member of that group

(See #5 for specification process.)

**Comment by micahscopes** [comment]
@sbazerque how does this look to you?

**Comment by sbazerque** [comment]
I think it clicks!

Some questions / doubts:

**Are we trying to do per-page permissions**? I'd leave that as a "nice to have" and do it at the end if there's time before the release. Same for other fine grained things we could come up with. Otherwise I'd do just wiki-wide permissions, and I'd have only two: **read** and **write**. Read would define who can join the sync peer group (owners, members, anybody), and write would define who can add pages to the `pages` set, change the blocks array in a page, and edit blocks (owners, members, anybody). So we'd have something like for the permissions config:

```
wiki.owners: HashedSet<Identity>
wiki.members: CausalSet<Identity>
wiki.readConfig: CausalSet<'Owners'|'Members'|'Anybody'>
wiki.writeConfig: CausalSet<'Owners'|'Members'|'Anybody'>
```
and then the config of the PeerGroup would depend upon `owners`, `members` and `readConfig`, while for the writing we should abstract the bit that depends on `owners`, `members` and `writeConfig` because we'll have to use it in at least the 3 places mentioned above to control wiki editing.

How does it look?

**Comment by sbazerque** [comment]
Actually the auth logic end ups being fairly compact using the (somewhat convoluted) functional interface, maybe there's not point in factoring it much. Here's how it looks now for the page block array:

https://github.com/hyperhyperspace/wiki-collab/blob/master/src/model/PageBlockArray.ts

```typescript

protected createWriteAuthorizer(author?: Identity): Authorizer {
    const openlyEditableAuth = 
           (this.editFlags as CausalSet<string>).createMembershipAuthorizer(WikiSpace.OpenlyEditableFlag);

    return Authorization.oneOf([super.createWriteAuthorizer(author), openlyEditableAuth]);
}
```

(That's a good example of `this.editFlags` being used as a causal source by the block array!)

(The block array receives `writers` and `mutableWriters` set as part of its standard config, and the wiki is passing `owners` and `members` as those, so they get used as causal soruces too in the call to `super.createWriteAuthorizer`)

**Comment by micahscopes** [comment]
This seems to be working really well.  I just tried out the `CausalReference` too and that also seems to be working!

**Comment by micahscopes** [comment]
I think this can be considered done now.
